### PR TITLE
google_connect controller modifcation to work with google-api-php (OAuth2 support)

### PR DESCRIPTION
**Pull request by samuelsh**
@AdwinTrave Please check it 

Thanks

### CODE REVIEW

**Comment by donjakobo** [comment]
@samuelsh I'm getting the following error (checked out your branch fresh and tried google login):  

    Unable to load the requested file: helpers/openid_helper.php

After walking through the code I see simple errors like:

		$this->load->helper ( array (
				'language',
				'account/ssl',
				'url',
				'account/openid' 
		) );

		$this->load->model ( array (
				'account/account_model',
				'account/account_openid_model' 
		) );

So I fixed the references to the files, then I get this error:

```
A PHP Error was encountered
Severity: Warning
Message: require_once(application/libraries/account/google-api-php-client/src/Google/autoload.php): failed to open stream: No such file or directory
Filename: account/connect_google.php
Line Number: 52
```

**Comment by donjakobo** [comment]
I kept digging at this, and this commit is incomplete, there is a lot more work to get it working, good try tho @samuelsh

**Comment by samuelsh** [comment]
Hi@donjakobo 
Sorry I forgot to fix "set_include_path"
It should contain correct absolute path to "google-api-php-client/src/Google", otherwise autolader will fail
So you need just set the correct absolute path and it will work.
I'll fix it and send a pull request again.

Thank You

**Comment by donjakobo** [comment]
There are still a few more issues (warnings / notices) down the line, the integration is not bug free, there is a block using the 

    $openid_google = array ();

that has errors because the array is empty and is referening an object incorrectly to assign values, try walking through the process and entering a  

    exit() or die()

**Comment by samuelsh** [comment]
@donjakobo 
Fixed thanks

**Comment by chego77** [comment]
$openid_google = array(
'fullname' => $userData->getName (),
'gender' => $userData->getGender (),
'language' => $userData->getLocale (),
'firstname' => $userData->getGivenName (), // google only
'lastname' => $userData->getFamilyName (), // google only
);

**Comment by samuelsh** [comment]
Thanks @chego77 
Should work now

**Comment by samuelsh** [comment]
@donjakobo @AdwinTrave 
Looks like all issues are fixed.
Do you like me to pull request again, or you'll check it first.

**Pull request closed without merging**
